### ISSUE TITLE
How to pass int-array argument / How to use "glp_get_mat_row(...)"?

### ISSUE THREAD

**Issue by sschnug** [biosustain/swiglpk#19]
First of all: very interesting project. The basic stuff is already working for me.

How would i use ```int glp_get_mat_row(glp_prob *lp, int i, int ind[],
double val[]);```. [GLPK API PDF](http://kam.mff.cuni.cz/~elias/glpk.pdf)

I don't have experience with SWIG, but after reading some stuff, i thought, i could pass any previously defined variable as argument and SWIG will take care. But everything i tried is failing.

Example A:

    a = np.zeros(nnz, dtype=int)
    b = np.zeros(nnz)
    length = glp_get_mat_row(lp, 1, a, b)
    # TypeError: in method 'glp_get_mat_row', argument 3 of type 'int []'

Example B:

    a = []
    b = []
    length = glp_get_mat_row(lp, 1, a, b)
    # TypeError: in method 'glp_get_mat_row', argument 3 of type 'int []'    

Example C:

    a = None
    b = None
    length = glp_get_mat_row(lp, 1, a, b)
    # WORKS, but of course i'm not retrieving the stuff i want to
    # Only length is returned as documented in GLPKs API

## Questions
- Am i doing something wrong? Or is this something not implemented / buggy?

Sascha

**Comment by cdiener** [comment]
SWIG wraps those basic C arrays with its own types. Those can be created with `intArray` and `doubleArray`. As described on GLPK indexing starts with 1 so you need to create them with length n+1. Using the example from the README the following works:

```Python
# Run example from READMe that defines a 3x3 LP matrix
a = intArray(4)
b = doubleArray(4)
length = glp_get_mat_row(lp, 1, a, b)
a[1] # gives correct entry
b[2] # dito
```

**Comment by sschnug** [comment]
@cdiener Thanks for that. That's a step in the right direction.

But how to cast these array to python-objects (list or numpy array)?
```list(a)``` and surprisingly ```np.array(a)``` won't work.

**Comment by sschnug** [comment]
@cdiener Thanks for all your insights!

As it's functional right now (with loop-based conversion) i will close this issue.

**Comment by cdiener** [comment]
Glad to help!

**Comment by cdiener** [comment]
If you are still interested in this, swiglpk now as `as_intArray` and `as_doubleArray` functions that convert a Python list to the respective type. As this is done in C it is much faster than the previously mentioned loop-based approach.
