### ISSUE TITLE
Set up automatic swiglpk releases that follow the GLPK version numbers

### ISSUE THREAD

**Issue by Midnighter** [biosustain/swiglpk#29]
Done:

* [ ] Always compile GLPK with GMP support
* [x] Use a mechanism (like RSS) to trigger swiglpk builds when a new GLPK release happened (or set up a cron job that checks the GLPK FTP server for a new version once a day/week)
* [x] Use the GLPK release version as the version for the swiglpk package

**Comment by phantomas1234** [comment]
https://travis-ci.org/biosustain/swiglpk/jobs/431540410 github release was indeed triggered

**Comment by phantomas1234** [comment]
Also, GMP was added to swiglpk binaries.
