### ISSUE TITLE
Create wheels for python 3.7

### ISSUE THREAD

**Issue by SigitaR** [biosustain/swiglpk#32]

**Comment by Midnighter** [comment]
@phantomas1234 does https://github.com/biosustain/swiglpk/commit/34f149ca8f1d384de3e5d088119121d7825485c9 fix this issue?

**Comment by Midnighter** [comment]
For some reason for linux there are only i686 wheels and no x86_64 ones. [See on PyPI](https://pypi.org/project/swiglpk/#files).
