### ISSUE TITLE
setup.py fails to locate an existing glpk.h in /usr/include.

### ISSUE THREAD

**Issue by Viech** [biosustain/swiglpk#40]
Whenever a new version of Python is released, until you provide wheels, users installing via `pip` will have to compile `swiglpk` using `setup.py`. In #39 and #36 people were having issues because they do not have `swig` installed. Even with `swig` installed, installation can fail due to bad portability of `setup.py` as detailed below.

When I run `python setup.py` on `4.65.1`, I get the following exception:
```shell
% python setup.py 
Trying to determine glpk.h location
glpk.h found at /include/glpk.h
Traceback (most recent call last):
  File "…/src/swiglpk/setup.py", line 57, in <module>
    copy_glpk_header()
  File "…/src/swiglpk/setup.py", line 48, in copy_glpk_header
    raise Exception('Could not find glpk.h! Maybe glpk or glpsol is not installed.')
Exception: Could not find glpk.h! Maybe glpk or glpsol is not installed.
```
The file `glpk.h` is installed but it is found in `/usr/include/glpk.h` as opposed to `/include/glpk.h`:
```
% ls /include/glpk.h
ls: cannot access '/include/glpk.h': No such file or directory
% ls /usr/include/glpk.h
/usr/include/glpk.h
```
The problem is in `setup.py` within `copy_glpk_header`. The function executes the `which glpsol` shell command, which on my installation of Arch Linux returns `/bin/glpsol`. Then, it replaces `bin` with `include`. However, while `/bin` is a symbolic link to `/usr/bin` where `glpsol` is actually installed, `/include` does not exist on Arch Linux. (The output `glpk.h found at /include/glpk.h` is wrong and should rather be `Expecting glpk.h at /include/glpk.h`.)

I'm not sure about the best way to locate `glpk.h` but I would suggest to first iterate over a list of common locations that includes the local directory and `/usr/include/`. If this fails, then you could still try to locate the header using `which` or even `gcc`.

**Comment by alexander-alleman** [comment]
Has a workaround been solved for this. I am trying to install on a cluster and getting this same error.

**Comment by Viech** [comment]
The workaround I chose wih my [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=python-swiglpk) is to copy `/usr/include/glpk.h` into the same directory as `setup.py` before running the latter.

**Comment by cdiener** [comment]
Sure, sounds good. Go ahead and send a PR with those changes. Maybe also put the `which` call in a try except and better error messages (what needs to be installed for compilation). I think the GCC strategy would not be that helpful since it only works for a small subset of OS/compiler combos. Something OS-agnostic would be better I would say.
