### ISSUE TITLE
Update CI/CD and create a release that supports Python 3.9+

### ISSUE THREAD

**Issue by cdiener** [biosustain/swiglpk#44]
@carrascomj This is just to track this. If it turns out to be complicated it may still be worthwhile to reactivate Travis just for a single build and deploy to get a release that works with Python 3.9. This would leave more time for a transition to GH actions.

**Comment by carrascomj** [comment]
#45 _reactivates_ travis but it is still timing-out for OSX. I will take a look at the problem there.

**Comment by cdiener** [comment]
Thanks for all your work on this. Looks like I was too optimistic with travis. The Mac problem looks like it has to do with outdated homebrew and that may be hard to fix. 

Also had a looks at your GH actions branch and it looks pretty good. Seems like the only thing is missing is to run everything in `config.sh` and `appveyor.yml` into `CIBW_BEFORE_BUILD_[OS]` options and installing swiglpk in the image.

**Comment by carrascomj** [comment]
After some failed tags, all wheels were sucessfully [added to PYPI](https://pypi.org/project/swiglpk/). However, the release was not added to the repository because the version comparison has not changed, so it will have to be uploaded manually (or wait until next GLPK version).

**Comment by cdiener** [comment]
Awesome, thanks for all the work on that!
