### ISSUE TITLE
Is possible build CBC from pure python?

### ISSUE THREAD

**Issue by SebastianJHM** [biosustain/swiglpk#55]
Hi SWIGLPK team.
I'm working in my project and I want to use [MIP](https://www.python-mip.com/) and [CBC](https://github.com/coin-or/Cbc) in the browser with [pyodide](https://github.com/pyodide). MIP function good because is a pure pyrhon library, the problem is CBC. I had trying with [cbcpy](https://pypi.org/project/cbcpy/) but the wheels are from specific OS. I know that this project is from GLPK, but I want to question if is possible build cbc whit native python wheels?

**Comment by Midnighter** [comment]
Not sure what you mean by from pure Python. CBC is written in C++ so it needs to be compiled for some platform...
