### ISSUE TITLE
Drop i686?

### ISSUE THREAD

**Issue by cdiener** [biosustain/swiglpk#60]
I wonder if we should still continue to support i686. Most modern OSs don't anymore and there should be very little hardware that uses it. But it does take up a large chunk of our wheel building and I'd rather spend this build time on building for ARM64. So I think we can drop it. Previous versions will still work on i686, this would only mean that no newer versions can be installed which should be okay for legacy hardware.

**Comment by Midnighter** [comment]
I agree, dropping it is a good idea.
