### ISSUE TITLE
No module named wheel.bdist_wheel

### ISSUE THREAD

**Issue by grundoc** [biosustain/swiglpk#9]
Error append when call python setup.py build

Can't build swiglpk without wheel.

I modified your setup.py to make it work (from line 58):
`
if os.name != 'nt':
    from distutils.command.build import build
    # from wheel.bdist_wheel import bdist_wheel

    # class CustomBdistWheel(bdist_wheel):
    #     def run(self):
    #         print('I am actually run!')
    #         self.run_command('build_ext')
    #         bdist_wheel.run(self)

    # custom_cmd_class['bdist_wheel'] = CustomBdistWheel

    class CustomBuild(build):
        def run(self):
            self.run_command('build_ext')
            build.run(self)

    custom_cmd_class['build'] = CustomBuild
`

**Comment by phantomas1234** [comment]
Thanks for reporting this. setup.py will not break now if wheel is not installed.
